<?php
/**
 * Created by PhpStorm.
 * User: alex
 * Date: 22.08.18
 * Time: 6:58
 */

namespace frontend\components;


use yii\validators\Validator;

class PhoneValidator extends Validator
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->message = "Неверно заполненое поле";
    }

    public function clientValidateAttribute($model, $attribute, $view)
    {
        parent::clientValidateAttribute($model, $attribute, $view); // TODO: Change the autogenerated stub

        return <<<JS
console.log(value);
JS;

    }

}