<?php

/**
 * Created by PhpStorm.
 * User: alex
 * Date: 21.08.18
 * Time: 16:58
 */

namespace frontend\components;

use frontend\models\SendForm;

class SendFormWidget extends \yii\base\Widget
{
    
    public $subject;
    
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $model = new SendForm();
        $model->subject = $this->subject;
        return $this->render('form', [
            'model' => $model,
        ]);
    }
}