<?php

/**
 * Created by PhpStorm.
 * User: Neo
 * Date: 06.08.18
 * Time: 12:58
 */

namespace frontend\components;

use frontend\models\SendCallBack;

class SendCallBackWidget extends \yii\base\Widget
{
	
    public $subject;
    public $messageLabel;
    public $placeholder = 'Номер телефона';
    public $textButton = 'Отправить';
    public $isLabels = false;
    public $idForm = 'send_phone';
    
    

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $model = new SendCallBack();
        $model->subject = $this->subject;
        return $this->render('send-call_back/form', [
            'model' => $model,
            'widget' => $this,
        ]);
    }
}