<?php

/**
 * Created by PhpStorm.
 * User: alex
 * Date: 21.08.18
 * Time: 16:58
 */

namespace frontend\components;

use frontend\models\SendForm;

class SendFormWidget extends \yii\base\Widget
{

    const SITE = 0;
    const SKYPE = 1;
    
    const FILES = 'files[]';
    const FILE = 'file';

    public $subject;
    public $messageLabel;
    public $messagePlaceholder = 'Ваше сообщение';
    public $textButton = 'Отправить бриф';
    public $isLabels = false;
    public $idForm = 'send_vacancy';
//    public $fileExtension = "jpg, jpeg, png, gif, zip, rar, pdf, doc, xls";
    public $fileExtension = "Максимальный размер - 2 мб";
    public $skypeOrSite = self::SKYPE;
    public $fileOrFiles = self::FILES;
    public $field;
    public $answer = 'Бриф отправлен!';
    public $id_answer = 'brief__mess';

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $model = new SendForm();
        $model->subject = $this->subject;

        if ($this->isLabels) $model->setRadioList();

        if ($this->skypeOrSite == self::SKYPE) $this->field = 'skype';
        if ($this->skypeOrSite == self::SITE) $this->field = 'site';

        return $this->render('send-form/form', [
            'model' => $model,
            'widget' => $this,
        ]);
    }
}